### ISSUE TITLE
Doesnt show up on Spotify version <1.2.13

### ISSUE THREAD

**Issue by fitsfer** [NickColley/spicetify-rewind#2]
Its just not there
![image](https://github.com/user-attachments/assets/e7b5ee17-4e2d-4d1b-a566-b3a1e590230b)

**Comment by NickColley** [comment]
Are you seeing anything in the dev tools error log?

**Comment by fitsfer** [comment]
![image](https://github.com/user-attachments/assets/a1fdae8a-1069-477a-ac7b-7df6e408b84a)

disabling other extensions didn't help

**Comment by NickColley** [comment]
What platform are you on?

**Comment by fitsfer** [comment]
Spotify for Windows (64 bit)
1.2.13.661.ga588f749
Spicetify v2.37.7

**Comment by NickColley** [comment]
Can you inspect the player controls and send me what the DOM looks like for you? Make sure to expand the button elements.

That's the only thing I can think of why it's broken

**Comment by NickColley** [comment]
Make sure to update your Spotify to the latest version as it may just be that too. I should think about making it less dependant on the current version though as it'll likely break in the future regardless...

**Comment by NickColley** [comment]
I'm going to try and resolve this so before you update let me give that a go first...

**Comment by NickColley** [comment]
Ok so if you try again, it should work now with this change:

https://github.com/NickColley/spicetify-rewind/commit/7e689a0b1ae1520add7da7e6dd75886e591bad61

**Comment by fitsfer** [comment]
No dice. It still doesn't show up
![image](https://github.com/user-attachments/assets/c97c9eb6-b9ba-45de-879f-a93837890359)

Updating Spotify isnt an option in my case because the version I'm on has a layout I much prefer to the newer ones. 
I'm not sure how to show you my DOM but you could probably reproduce this issue with an install of [1.2.13.661.](https://spotify.en.uptodown.com/windows/download/103659700)

**Comment by NickColley** [comment]
To show me your DOM you want to use the elements tab:

![image](https://github.com/user-attachments/assets/ce5acf85-33a2-4fcc-9421-6ee04581c59d).

I'll try to install your specific version in the meantime and have a poke.

**Comment by fitsfer** [comment]
![image](https://github.com/user-attachments/assets/474c5ff6-fa5c-4981-9bda-619e73fc32c3)

This?

**Comment by NickColley** [comment]
Based on that the new code should work so it might be that you're still downloading the previous version, I'm new to extensions so not sure how to force the latest version but you could try deleting the extension, closing the application and then reloading it. Then seeing if it'll start working.

I'm trying to see if I can install your version regardless but I'm on Linux so might not be possible.

**Comment by NickColley** [comment]
If you do see an error again, can you please press the hyperlink in the error should read "index.js", and share that with me so I can confirm which version of the extension is being ran.

I just looked at the Linux versions and the version you're running is very old so it's not available unfortunately.

I'll try to help you get it working but ultimately you may have to update for this extension if I've exhausted the options.

That said based on what you've shown me the code should now work so fingers crossed it'll start working if you reload everything properly.

**Comment by fitsfer** [comment]
![image](https://github.com/user-attachments/assets/a0e28cf4-a2f0-497e-b802-836496e68b06)

It started working after I manually applied index.js through PowerShell, and now it appears after installing it with marketplace!

**Comment by fitsfer** [comment]
It also works functionally, but there is a tiny pop at the end of the rewind sfx that's unrelated but other than that it works
